export default function Site(){return(<div className='min-h-screen bg-slate-50 text-slate-900'><header className='max-w-6xl mx-auto px-6 py-16'>
  <h1 className='text-4xl md:text-5xl font-semibold tracking-tight'>RC Strategic Consulting</h1>
  <p className='mt-4 text-xl font-medium'>Richard Cassella, Founder & Principal Advisor</p>
  <p className='mt-6 text-xl max-w-3xl'>Independent, board-level advisory supporting leaders through high-stakes strategic and technology decisions.</p>
</header><main className='max-w-6xl mx-auto px-6 grid gap-20'><section><h2 className='text-2xl font-semibold mb-6'>Strategic Advisory Focus</h2><ul className='space-y-4 max-w-3xl text-lg'><li>• Board and executive-level strategic decision support</li><li>• Technology and platform strategy, selection, and risk assessment</li><li>• Organizational and operational clarity during periods of change</li><li>• Independent perspective on complex, cross-functional initiatives</li></ul></section><section><h2 className='text-2xl font-semibold mb-6'>How I Engage</h2><p className='max-w-3xl text-lg'>I work directly with founders, boards, and senior executives as a trusted, independent advisor. Engagements are intentionally limited, discreet, and focused on decisions that materially impact enterprise value. My role is not execution-for-hire, but strategic clarity—bringing structure, judgment, and experience to moments that matter.</p></section><section>
  <h2 className='text-2xl font-semibold mb-6'>Selected Experience</h2>
  <ul className='space-y-4 max-w-3xl text-lg'>
    <li>• Key advisor to the founder of a specialized financial software company, serving as a trusted partner for both tactical execution and long-range strategic decision-making.</li>
    <li>• Played a senior leadership role during a period of significant growth, supporting the company’s expansion from fewer than 100 clients to more than 1,500 clients, culminating in its acquisition by a large financial services firm.</li>
  </ul>
</section>
<section>
  <h2 className='text-2xl font-semibold mb-6'>About Richard Cassella</h2>
  <p className='max-w-3xl text-lg'>Richard Cassella is the Founder and Principal Advisor of RC Strategic Consulting. He partners with boards, founders, and senior executives during pivotal moments—where strategic direction, technology investment, and organizational risk intersect.</p>
  <p className='max-w-3xl text-lg mt-4'>Drawing on experience advising organizations ranging from specialized investment teams to complex, scaled enterprises, Richard brings a calm, independent perspective to high-consequence decisions. His work is defined by discretion, structured thinking, and a focus on outcomes that materially impact enterprise value.</p>
</section><section><h2 className='text-2xl font-semibold mb-6'>Contact</h2><p className='max-w-3xl text-lg'>For board-level or executive advisory inquiries, please reach out to discuss fit and scope.</p><a href='mailto:contact@rc-strategic.consulting' className='inline-block mt-6 px-8 py-4 rounded-2xl bg-slate-900 text-white text-lg'>Contact Me</a></section></main><footer className='max-w-6xl mx-auto px-6 py-12 text-sm text-slate-500'>© {new Date().getFullYear()} RC Strategic Consulting</footer></div>)}
